name: JDPoolsApplication
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+3

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: "^2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0
  pdf: ^3.4.2
  open_file: ^3.1.0
  intl: ^0.17.0
  path_provider: ^1.6.5
  flutter_full_pdf_viewer: ^1.0.6
  image_picker: ^0.6.0+9
  flutter_masked_text: ^0.8.0
  geocoding: ^1.0.2
  flutter_google_places: 0.2.6
  grouped_buttons: ^1.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  font_awesome_flutter:
#  firebase_auth: ^0.18.0+1
  camera: ^0.5.2+1
  firebase_ml_vision: ^0.12.0+2
  firebase_messaging: ^7.0.3
  geolocator: ^6.2.1
  provider: ^5.0.0
  flutter_swiper : ^1.1.6
  google_maps_flutter: any
  flutter_svg: ^0.22.0 # help us to use SVG in our app
  smooth_star_rating: 1.1.1
  flutter_launcher_icons: ^0.9.1
  shared_preferences: ^0.5.12
  get_storage: ^1.4.0
  flutter_session: ^0.1.1
  promptpay: ^1.1.0
  qr_flutter: ^4.0.0
  fk_toggle: ^0.1.4
  transparent_image: ^2.0.1
  cached_network_image: ^2.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  progress_dialog: ^1.2.4
  persistent_bottom_nav_bar: ^4.0.0

flutter_icons:
    image_path: "assets/images/logo2.png"
    android: true
    ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/shopping.svg
    - assets/icons/home.svg
    - assets/images/logo2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
      - family: Muli
        fonts:
          - asset: assets/fonts/muli/Muli.ttf
          - asset: assets/fonts/muli/Muli-Bold.ttf
            weight: 700
          - asset: assets/fonts/muli/Muli-Light.ttf
            weight: 300

      - family: Kanit
        fonts:
          - asset: assets/fonts/Kanit/Kanit-Regular.ttf
          - asset: assets/fonts/Kanit/Kanit-Italic.ttf
            style: italic
          - asset: assets/fonts/Kanit/Kanit-Bold.ttf
            weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
